
//ATIVIDADE: ANALIESE DE NOTAS DE ALUNOS

let notas = [6.0,7.0,6.0];

if(notas[0]>=7){
console.log("aprovado primeira nota",  notas[0] )
} else if(notas[0]<4){
    console.log("reprovado pela primeira nota",  notas[0])
} else if(notas[0]>4){
    console.log("aprovado pela recuperecao, primeira nota",  notas[0])
}   

if(notas[1]>=7){
    console.log("aprovado pela segunda nota",  notas[1])
}else if(notas[1]<4){
    console.log("reprovado pela segunda nota",  notas[1])
}else if(notas[1]>4){
    console.log("aprovado pela recuperacao, segunada nota",  notas[1])
}
if(notas[2]>=7){
    console.log("aprovado pela segunda nota", notas[2])
}else if(notas[2]<4){
    console.log("reprovado pela segunda nota",  notas[2])
}else if(notas[2]>4){
    console.log("aprovado pela recuperacao, segunada nota", notas[2])
}


