// atividade 1: verificar primeiro numero


let numero = [12,14,59];

 if(numero[0]> numero[1]){

    console.log(numero[0], "valor maior que" ,numero[1])
 
        }else if(numero[1]>numero[0]){

    console.log(numero[1], "valor maior que", numero[0])

         }if(numero[1]>numero[2]){

          
    console.log(numero[1], "valor maior que", numero[2])

         }else
            {
    console.log(numero[1],"valor menor que", numero[2])
 }